### ISSUE TITLE
Aligning fields across schema

### ISSUE THREAD

**Issue by gmoore016** [sul-cidr/patent_data_extractor#12]
Hi @simonwiles --

Hope you're doing well! I've been having a bit of trouble finding an easy solution to this and wanted to check in to see if you had any ideas. 

It turns out that when moving from one schema to the next, there's no guarantee the proper information will end up in the appropriate column (in retrospect perhaps this is obvious, but I hadn't realized until I was looking through the data). 

As an example, when we parse `ipg050111.xml` using the `grants-0506` schema and then `ipg081223.xml` using the `grants-0613` schema, `filing _type` ends up in `examiner1_dep`, among several other alignment issues in the right half of the table. 

I think this stems from us simply `append`ing the csv instead of aligning the columns first. I spent some time looking at config-file based solutions, but figure those are both (a) non-obvious and (b) fragile, so wanted to check with you about a parser-based solution. 

What seems like the most straightforward answer to me is looking at the columns of the existing CSV, aligning any columns of the active CSV with the same name, and then generating new columns for any where the names differ. Does that make sense? Let me know if you have other ideas.

Thanks!

**Comment by simonwiles** [comment]
Hi Gideon,

This is something that can be addressed the parser script, certainly, but I'm not sure that's optimal.  What's the use-case for parsing all the data into one giant (and unwieldy) CSV file?  If your ultimate target is a database of some kind, then parsing each set of files that conform to an individual schema (or even smaller groups) is likely to be a much better way to go about it (when I parsed the WoS data into PostgreSQL, I parsed and created flat files for each year at a time, and then dumped them into PostgreSQL from there).  It **is** possible to configure the schema YAML files in such a way that naïvely concatenate-able CSV files are generated, but you're absolutely right about both your (a) and your (b) -- not ideal.  So my suggestion (and my original intention -- although I think when I wrote the first pass of this script I hadn't realized you had multiple incompatible schemas) is that you would use the parser to generate multiple CSVs that would then be loaded into a database or another analysis environment.

If this won't work for you for whatever reason, I can adjust the script the realign the columns as needed -- there will be some overhead to this, though.  CSV files don't really work this way, so there are two options.  1) is as you suggest, but note that where new columns must be introduced, this will require rewriting the header line and (for a CSV file that is maximally compatible) rewriting every existing line to add empty values corresponding to the new fields -- this is hacky and not terribly performant; 2) would be to parse all the schema files before writing anything -- this would be preferable from a performance and scripting point-of-view, but may present logistical and workflow problems (i.e. you have to have them all ready at the beginning).

If you're very keen to have everything in one dataset directly out of the parser, a better idea might be to go straight to a database and use the sqlite format.  Sqlite dbs can be directly imported in most places CSV files can be used, or you can dump CSVs from the tables in the sqlite db, if you really need to.  Right now if you try to write parser results from incompatible schemas to the same sqlite db (with `--output-type sqlite`) the columns will be aligned correctly, but the DB structure will be defined by the schema written first -- i.e., you'll get the fieldset from the first batch, and new fields encountered in subsequent batches will not be written.  However, because it's a proper database format, fixing this would be much more elegant than either 1) or 2) above.  If the sqlite performance is an issue, it's likely I can optimize the INSERT performance somewhat.

What do you reckon?  I should have time to address changes to the parser without too much delay if you'd like to go that route.


simon

**Comment by gmoore016** [comment]
Hi Simon--

Thanks so much for being so thoughtful here! Based on your analysis, it sounds like we're really bumping up against the limits of the CSV format here. One of our core goals is to get everything into the same system, so we think your suggestion to move fully to SQLite makes a lot of sense. Given that, could you look into a way to incorporate new fields into the SQLite output as we find them? Once that's working we can look into whether performance ends up being a constraint.

As always, happy to answer any questions you run into in the process! Thank you again for your help here.

Gideon

**Comment by simonwiles** [comment]
Just an update on this: I've hit a bug of sorts on an upstream library I've been using for this.  I've "fixed" it, but only by hacking the upstream dependency.  I'd like to discuss/resolve this with the author of that library, but in the mean time I can bundle my hacked version as part of the repository here if you'd like to get started trying it?

**Comment by gmoore016** [comment]
That sounds great, thanks! Let us know if there's anything we should keep an eye out for in the meantime.

**Comment by simonwiles** [comment]
Just this minute raised a PR against the upstream library.  Author is responsive, so expecting it to be merged and a new version released fairly quickly (assuming I haven't overlooked anything in the fix).

**Comment by simonwiles** [comment]
So the new commits address this problem when `--output-type=sqlite`, at least.  I'm thinking there should be a warning produced by the code and/or in the documentation about the CSV case.  I still feel that the use of a script like this to produce CSV files that combine rows parsed against conflicting schemas is a bit of an anti-pattern, so I'm not sure that "fixing" it in that sense is really the way to go.  Happy to continue the discussion here, in another issue, or elsewhere, though.
