### ISSUE TITLE
Memory allocation failure

### ISSUE THREAD

**Issue by gmoore016** [sul-cidr/patent_data_extractor#9]
Hi @simonwiles --

We're running the parser with the same configuration as in #8 on all archives 2001-2004 (that is, all those which match the wildcard pg*, since in 2005 they switched to the new schema ipg*). It works (very!) well up until `pg030318` when I get the error

```
Unable to parse XML document ending at line 1386541 (enable debugging -v to dump doc to console):
        Memory allocation failed, line 506, column 40
```

Strangely, we don't get this error when running the parser on that document alone, only when running it with the full set. Moreover, we then get this error maybe a hundred times on consecutive patents within that file, leading to massive crash dumps. 

Do you have any ideas what the problem is here? I had thought it was memory related, but I doubled the memory allocation of each process and got the same error on the same file.

**Comment by simonwiles** [comment]
So I've been down a bit of a rabbit hole here, but I have come up with a diagnosis and a solution.  I'll write it up and commit it when I've had some sleep (seriously broken sleep, of course, but that's the only kind I'm going to get for a while!) :)

**Comment by simonwiles** [comment]
So you're right -- despite the less than helpful error message from lxml, this clearly isn't being caused by the process running out of memory _per se_.  Googling and checking the usual places I found a few references to people having what appear to be similar problems, but no resolutions offered.

`lxml` is a python binding for `libxml2`, so I started digging through the source code for `libxml2`.  It seems that `lxml` uses a single local `libxml2` dictionary for lookup and retrieval of tag names, attributes, and `xml:id`s that is not reset on a per-doc basis, and so it accumulates over the run.

As a security measure to prevent DOS-style attacks, `lmbxml2` defines a `XML_MAX_DICTIONARY_LIMIT` constant which prevents a malicious or out-of-control process from crashing an entire system.  [It's hardcoded in the source code for `lxml2` to a very conservative 10,000,000 entries](https://gitlab.gnome.org/GNOME/libxml2/-/blob/master/include/libxml/parserInternals.h#L55-63), and this is the limit that's being hit and causing the "Memory allocation failed" exception to be thrown (for every subsequent attempt to store a key).

Fortunately `lbxml2` provides a `XML_PARSE_HUGE` option to override this limit, and `lxml` exposes this to the parser constructor as ['huge_tree`](https://lxml.de/parsing.html#parser-options), and although you'd never guess it's related to this issue from the documentation ("disable security restrictions and support very deep trees and very long text content"), enabling this option does seem to solve the problem.

I'm not concerned that overriding this limit will cause memory problems (the script is very memory efficient), but I am a little worried that an unfettered global dictionary that grows over the course of the run may have performance implications.  In an attempt to mitigate this I've also passed `collect_ids=False` to the parser constructor, and I've seen a small but significant benefit in my tests.
